sudo: true
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
before_install:
  # SERD
  - wget http://download.drobilla.net/serd-0.24.0.tar.bz2
  - tar -xjvf serd-0.24.0.tar.bz2
  - pushd serd-0.24.0 && ./waf configure && ./waf && sudo ./waf install && popd
  # Raptor
  - wget http://download.librdf.org/source/raptor2-2.0.15.tar.gz
  - tar -xzvf raptor2-2.0.15.tar.gz
  - pushd raptor2-2.0.15 && ./configure && make -j2 && sudo make install && popd
script:
  - cd hdt-lib
  - make -j2
  - tools/hdtSearch -q 0 data/literals.hdt
